### ISSUE TITLE
`pglogical` vs `pgoutput`

### ISSUE THREAD

**Issue by judahrand** [replicase/pgcapture#4]
I was wondering what the reasons behind using the `pglogical_output` plugin over the standard `pgoutput` plugin were?

**Comment by judahrand** [comment]
Ah, is it due to the desire to track DDL changes?

**Comment by judahrand** [comment]
Although, that looks like it is done by the `pgcapture` extension

**Comment by rueian** [comment]
Hi, @judahrand 

Yes, DDL capture is done by pgcapture extension.

The reason behind using pglogical is pgoutput was introduced in PostgreSQL 10 and it didn’t support binary representation until PostgreSQL 14.

By using pglogical, pgcapture can support binary logical replication with PostgreSQL 9.4 to 13.

Since now pgoutput supports binary representation in PostgreSQL 14, I will also make pgcapture support pgoutput in future versions.

**Comment by judahrand** [comment]
This also looks like a potentially exciting development for the future!

https://postgrespro.com/list/thread-id/2590610

**Comment by rueian** [comment]
Hi @judahrand,

Thanks to @KennyChenFight, we can now use the standard pgoutput plugin to decode changes on PostgreSQL 14 and above!
